openapi: 3.2.0
info:
  title: Hyperion History API for UPLAND Chain Node API
  description: '### Scalable Full History API Solution for EOSIO based blockchains

    *Made with ♥️ by EOS Rio*

    ***

    #### Current Chain: UPLAND Chain

    #### Provided by UPLAND

    #### Health API: https://10.0.3.200:7000/v2/health'
  version: 3.3.10
servers:
- url: https://chain-history.upland.me
tags:
- name: Node
paths:
  /v1/node/get_supported_apis:
    get:
      summary: Get list of supported APIs
      tags:
      - Node
      responses:
        '200':
          description: Default Response
      operationId: getV1NodeGetSupportedApis
      x-operation-id-source: derived
